apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
  namespace: ecom
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  JWT_EXPIRATION: "3600000"
  JWT_REFRESH_EXPIRATION: "86400000"
  KAFKA_CONCURRENCY: "3"
  PRODUCT_SERVICE_BASE_URL: http://product-service:8082
  OUTBOX_PUBLISHER_FIXED_DELAY_MS: "2000"
  OUTBOX_PUBLISHER_BATCH_SIZE: "200"
  OUTBOX_PUBLISHER_MAX_ATTEMPTS: "20"
  OUTBOX_PUBLISHER_IN_PROGRESS_TIMEOUT_MS: "60000"
