apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecom
resources:
  - namespace.yaml
  - configmap.yaml
  - customer-web-deployment.yaml
  - admin-panel-deployment.yaml
  - nginx-gateway.yaml
  - ingress.yaml
  - user-service-deployment.yaml
  - product-service-deployment.yaml
  - inventory-service-deployment.yaml
  - order-service-deployment.yaml
  - payment-service-deployment.yaml
