apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/babe8901/user-service
    newTag: latest
  - name: ghcr.io/babe8901/product-service
    newTag: latest
  - name: ghcr.io/babe8901/inventory-service
    newTag: latest
  - name: ghcr.io/babe8901/order-service
    newTag: latest
  - name: ghcr.io/babe8901/payment-service
    newTag: latest
  - name: ghcr.io/babe8901/customer-web
    newTag: latest
  - name: ghcr.io/babe8901/admin-panel
    newTag: latest
