apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  namespace: ecom
spec:
  tls:
    - hosts:
        - ecom.example.com
      secretName: ecom-tls
  rules:
    - host: ecom.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 80
